apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-kafka

resources:
  - example-kafka.yaml
  - example-service-registry.yaml
  - example-service-registry-route.yaml
  - topics